name: SinglePlayerSleep
main: com.github.joelgodofwar.sps.SinglePlayerSleep
version: 1.13_2.13.45.D6
author: JoelGodOfWar(JoelYahwehOfWar)
api-version: 1.13
softdepend: [BloodMoon,VentureChat,Essentials]

commands:
  spscancel:
    description: Cancels Single Player Sleep. Does not change to day.
    usage: /<command>
  sleep:
    description: Notifies players that player wishes to sleep.
    usage: /<command>
  dayskip:
    description: Notifies players that player wishes to dayskip.
    usage: /<command>
  sps:
    description: Shows SinglePlayerSleep help.
    usage: /<command>
  spsbloodmoon:
    description: Disables sleep during a blood moon, console only.
    usage: /<command>
  clearrain:
    description: Clears rain, when it is not night and there is a rain storm.
    usage: /<command>

permissions:
  sps.hermits:
    description: Allows one player to change the time to day when using a bed. Without clearing local difficulty.
    default: true
  sps.unrestricted:
    description: Allows the player to sleep uninterrupted. Other players will not be able to cancel it.
    default: false
  sps.downfall:
    description: Clears Downfall upon SPS sleep.
    default: false
  sps.thunder:
    description: Clears Thunderstorm upon SPS sleep
    default: false
  sps.cancel:
    description: Allows canceling Single Player Sleep.
    default: true
  sps.command:
    description: Allows player to use the /sleep command, instead of a bed.
    default: op
  sps.update:
    description: Allows the player to check for updates.
    default: op
  sps.op:
    description: Overrides all permissions.
    default: false
  sps.showUpdateAvailable:
    description: Shows player that there is a version update.
    default: op
  sps.dayskipper:
    description: Allows one player to change the time to night when using a bed. Without clearing local difficulty.
    default: false
  sps.dayskipcommand:
    sps.command:
    description: Allows player to use the /dayskip command, instead of a bed.
    default: op